name: Build nix cache

on:
  workflow_dispatch:

jobs:
  build-and-cache:
    strategy:
      matrix:
        include:
          - job-name: macos-homemanager
            os-label: macos-latest-large
            nix-flake-output: ".#homeConfigurations.mac-legacy.activationPackage"
      fail-fast: false

    name: ${{ matrix.job-name }}
    runs-on: ${{ matrix.os-label }}
    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: dots
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Add nix-community cache
        run: cachix use nix-community

      - name: Build ${{ matrix.job-name }} on ${{ matrix.os-label }}
        run: nix build --show-trace --json --keep-going "${{ matrix.nix-flake-output }}"
